/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogSlugRouteImport } from './routes/catalog/$slug'
import { Route as AuthSystemRouteImport } from './routes/_auth/system'
import { Route as AuthRubricsRouteImport } from './routes/_auth/rubrics'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLmsRouteImport } from './routes/_auth/lms'
import { Route as AuthGamificationRouteImport } from './routes/_auth/gamification'
import { Route as AuthFraudRouteImport } from './routes/_auth/fraud'
import { Route as AuthEnterpriseRouteImport } from './routes/_auth/enterprise'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthSubmissionsIndexRouteImport } from './routes/_auth/submissions/index'
import { Route as AuthQuizTemplatesIndexRouteImport } from './routes/_auth/quiz-templates/index'
import { Route as AuthQuestionsIndexRouteImport } from './routes/_auth/questions/index'
import { Route as AuthCoursesIndexRouteImport } from './routes/_auth/courses/index'
import { Route as AuthCertificatesIndexRouteImport } from './routes/_auth/certificates/index'
import { Route as AuthAssignmentsIndexRouteImport } from './routes/_auth/assignments/index'
import { Route as AuthSubmissionsIdRouteImport } from './routes/_auth/submissions/$id'
import { Route as AuthQuizTemplatesIdRouteImport } from './routes/_auth/quiz-templates/$id'
import { Route as AuthQuestionsNewRouteImport } from './routes/_auth/questions/new'
import { Route as AuthCoursesIdRouteImport } from './routes/_auth/courses/$id'
import { Route as AuthCertificatesCertNoRouteImport } from './routes/_auth/certificates/$certNo'
import { Route as AuthAssignmentsIdRouteImport } from './routes/_auth/assignments/$id'
import { Route as AuthQuestionsIdEditRouteImport } from './routes/_auth/questions/$id_.edit'
import { Route as AuthCoursesIdLearnRouteImport } from './routes/_auth/courses/$id_.learn'
import { Route as AuthCoursesIdCurriculumRouteImport } from './routes/_auth/courses/$id_.curriculum'
import { Route as AuthAssignmentsIdTakeRouteImport } from './routes/_auth/assignments/$id_.take'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSystemRoute = AuthSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRubricsRoute = AuthRubricsRouteImport.update({
  id: '/rubrics',
  path: '/rubrics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLmsRoute = AuthLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGamificationRoute = AuthGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFraudRoute = AuthFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEnterpriseRoute = AuthEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubmissionsIndexRoute = AuthSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuizTemplatesIndexRoute = AuthQuizTemplatesIndexRouteImport.update({
  id: '/quiz-templates/',
  path: '/quiz-templates/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestionsIndexRoute = AuthQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesIndexRoute = AuthCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCertificatesIndexRoute = AuthCertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssignmentsIndexRoute = AuthAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubmissionsIdRoute = AuthSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuizTemplatesIdRoute = AuthQuizTemplatesIdRouteImport.update({
  id: '/quiz-templates/$id',
  path: '/quiz-templates/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestionsNewRoute = AuthQuestionsNewRouteImport.update({
  id: '/questions/new',
  path: '/questions/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesIdRoute = AuthCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCertificatesCertNoRoute = AuthCertificatesCertNoRouteImport.update({
  id: '/certificates/$certNo',
  path: '/certificates/$certNo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssignmentsIdRoute = AuthAssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestionsIdEditRoute = AuthQuestionsIdEditRouteImport.update({
  id: '/questions/$id_/edit',
  path: '/questions/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesIdLearnRoute = AuthCoursesIdLearnRouteImport.update({
  id: '/courses/$id_/learn',
  path: '/courses/$id/learn',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesIdCurriculumRoute = AuthCoursesIdCurriculumRouteImport.update({
  id: '/courses/$id_/curriculum',
  path: '/courses/$id/curriculum',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssignmentsIdTakeRoute = AuthAssignmentsIdTakeRouteImport.update({
  id: '/assignments/$id_/take',
  path: '/assignments/$id/take',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthDashboardRoute
  '/enterprise': typeof AuthEnterpriseRoute
  '/fraud': typeof AuthFraudRoute
  '/gamification': typeof AuthGamificationRoute
  '/lms': typeof AuthLmsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/reports': typeof AuthReportsRoute
  '/rubrics': typeof AuthRubricsRoute
  '/system': typeof AuthSystemRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/assignments/$id': typeof AuthAssignmentsIdRoute
  '/certificates/$certNo': typeof AuthCertificatesCertNoRoute
  '/courses/$id': typeof AuthCoursesIdRoute
  '/questions/new': typeof AuthQuestionsNewRoute
  '/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/submissions/$id': typeof AuthSubmissionsIdRoute
  '/assignments/': typeof AuthAssignmentsIndexRoute
  '/certificates/': typeof AuthCertificatesIndexRoute
  '/courses/': typeof AuthCoursesIndexRoute
  '/questions/': typeof AuthQuestionsIndexRoute
  '/quiz-templates/': typeof AuthQuizTemplatesIndexRoute
  '/submissions/': typeof AuthSubmissionsIndexRoute
  '/assignments/$id/take': typeof AuthAssignmentsIdTakeRoute
  '/courses/$id/curriculum': typeof AuthCoursesIdCurriculumRoute
  '/courses/$id/learn': typeof AuthCoursesIdLearnRoute
  '/questions/$id/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthDashboardRoute
  '/enterprise': typeof AuthEnterpriseRoute
  '/fraud': typeof AuthFraudRoute
  '/gamification': typeof AuthGamificationRoute
  '/lms': typeof AuthLmsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/reports': typeof AuthReportsRoute
  '/rubrics': typeof AuthRubricsRoute
  '/system': typeof AuthSystemRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog': typeof CatalogIndexRoute
  '/assignments/$id': typeof AuthAssignmentsIdRoute
  '/certificates/$certNo': typeof AuthCertificatesCertNoRoute
  '/courses/$id': typeof AuthCoursesIdRoute
  '/questions/new': typeof AuthQuestionsNewRoute
  '/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/submissions/$id': typeof AuthSubmissionsIdRoute
  '/assignments': typeof AuthAssignmentsIndexRoute
  '/certificates': typeof AuthCertificatesIndexRoute
  '/courses': typeof AuthCoursesIndexRoute
  '/questions': typeof AuthQuestionsIndexRoute
  '/quiz-templates': typeof AuthQuizTemplatesIndexRoute
  '/submissions': typeof AuthSubmissionsIndexRoute
  '/assignments/$id/take': typeof AuthAssignmentsIdTakeRoute
  '/courses/$id/curriculum': typeof AuthCoursesIdCurriculumRoute
  '/courses/$id/learn': typeof AuthCoursesIdLearnRoute
  '/questions/$id/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/enterprise': typeof AuthEnterpriseRoute
  '/_auth/fraud': typeof AuthFraudRoute
  '/_auth/gamification': typeof AuthGamificationRoute
  '/_auth/lms': typeof AuthLmsRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/rubrics': typeof AuthRubricsRoute
  '/_auth/system': typeof AuthSystemRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/_auth/assignments/$id': typeof AuthAssignmentsIdRoute
  '/_auth/certificates/$certNo': typeof AuthCertificatesCertNoRoute
  '/_auth/courses/$id': typeof AuthCoursesIdRoute
  '/_auth/questions/new': typeof AuthQuestionsNewRoute
  '/_auth/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/_auth/submissions/$id': typeof AuthSubmissionsIdRoute
  '/_auth/assignments/': typeof AuthAssignmentsIndexRoute
  '/_auth/certificates/': typeof AuthCertificatesIndexRoute
  '/_auth/courses/': typeof AuthCoursesIndexRoute
  '/_auth/questions/': typeof AuthQuestionsIndexRoute
  '/_auth/quiz-templates/': typeof AuthQuizTemplatesIndexRoute
  '/_auth/submissions/': typeof AuthSubmissionsIndexRoute
  '/_auth/assignments/$id_/take': typeof AuthAssignmentsIdTakeRoute
  '/_auth/courses/$id_/curriculum': typeof AuthCoursesIdCurriculumRoute
  '/_auth/courses/$id_/learn': typeof AuthCoursesIdLearnRoute
  '/_auth/questions/$id_/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/enterprise'
    | '/fraud'
    | '/gamification'
    | '/lms'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/rubrics'
    | '/system'
    | '/catalog/$slug'
    | '/catalog/'
    | '/assignments/$id'
    | '/certificates/$certNo'
    | '/courses/$id'
    | '/questions/new'
    | '/quiz-templates/$id'
    | '/submissions/$id'
    | '/assignments/'
    | '/certificates/'
    | '/courses/'
    | '/questions/'
    | '/quiz-templates/'
    | '/submissions/'
    | '/assignments/$id/take'
    | '/courses/$id/curriculum'
    | '/courses/$id/learn'
    | '/questions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/enterprise'
    | '/fraud'
    | '/gamification'
    | '/lms'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/rubrics'
    | '/system'
    | '/catalog/$slug'
    | '/catalog'
    | '/assignments/$id'
    | '/certificates/$certNo'
    | '/courses/$id'
    | '/questions/new'
    | '/quiz-templates/$id'
    | '/submissions/$id'
    | '/assignments'
    | '/certificates'
    | '/courses'
    | '/questions'
    | '/quiz-templates'
    | '/submissions'
    | '/assignments/$id/take'
    | '/courses/$id/curriculum'
    | '/courses/$id/learn'
    | '/questions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_auth/dashboard'
    | '/_auth/enterprise'
    | '/_auth/fraud'
    | '/_auth/gamification'
    | '/_auth/lms'
    | '/_auth/onboarding'
    | '/_auth/profile'
    | '/_auth/reports'
    | '/_auth/rubrics'
    | '/_auth/system'
    | '/catalog/$slug'
    | '/catalog/'
    | '/_auth/assignments/$id'
    | '/_auth/certificates/$certNo'
    | '/_auth/courses/$id'
    | '/_auth/questions/new'
    | '/_auth/quiz-templates/$id'
    | '/_auth/submissions/$id'
    | '/_auth/assignments/'
    | '/_auth/certificates/'
    | '/_auth/courses/'
    | '/_auth/questions/'
    | '/_auth/quiz-templates/'
    | '/_auth/submissions/'
    | '/_auth/assignments/$id_/take'
    | '/_auth/courses/$id_/curriculum'
    | '/_auth/courses/$id_/learn'
    | '/_auth/questions/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/system': {
      id: '/_auth/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthSystemRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rubrics': {
      id: '/_auth/rubrics'
      path: '/rubrics'
      fullPath: '/rubrics'
      preLoaderRoute: typeof AuthRubricsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lms': {
      id: '/_auth/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof AuthLmsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gamification': {
      id: '/_auth/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AuthGamificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fraud': {
      id: '/_auth/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof AuthFraudRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/enterprise': {
      id: '/_auth/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof AuthEnterpriseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/submissions/': {
      id: '/_auth/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthSubmissionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quiz-templates/': {
      id: '/_auth/quiz-templates/'
      path: '/quiz-templates'
      fullPath: '/quiz-templates/'
      preLoaderRoute: typeof AuthQuizTemplatesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/questions/': {
      id: '/_auth/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthQuestionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/': {
      id: '/_auth/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthCoursesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/certificates/': {
      id: '/_auth/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthCertificatesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assignments/': {
      id: '/_auth/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AuthAssignmentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/submissions/$id': {
      id: '/_auth/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthSubmissionsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quiz-templates/$id': {
      id: '/_auth/quiz-templates/$id'
      path: '/quiz-templates/$id'
      fullPath: '/quiz-templates/$id'
      preLoaderRoute: typeof AuthQuizTemplatesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/questions/new': {
      id: '/_auth/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof AuthQuestionsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$id': {
      id: '/_auth/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthCoursesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/certificates/$certNo': {
      id: '/_auth/certificates/$certNo'
      path: '/certificates/$certNo'
      fullPath: '/certificates/$certNo'
      preLoaderRoute: typeof AuthCertificatesCertNoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assignments/$id': {
      id: '/_auth/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AuthAssignmentsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/questions/$id_/edit': {
      id: '/_auth/questions/$id_/edit'
      path: '/questions/$id/edit'
      fullPath: '/questions/$id/edit'
      preLoaderRoute: typeof AuthQuestionsIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$id_/learn': {
      id: '/_auth/courses/$id_/learn'
      path: '/courses/$id/learn'
      fullPath: '/courses/$id/learn'
      preLoaderRoute: typeof AuthCoursesIdLearnRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$id_/curriculum': {
      id: '/_auth/courses/$id_/curriculum'
      path: '/courses/$id/curriculum'
      fullPath: '/courses/$id/curriculum'
      preLoaderRoute: typeof AuthCoursesIdCurriculumRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assignments/$id_/take': {
      id: '/_auth/assignments/$id_/take'
      path: '/assignments/$id/take'
      fullPath: '/assignments/$id/take'
      preLoaderRoute: typeof AuthAssignmentsIdTakeRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEnterpriseRoute: typeof AuthEnterpriseRoute
  AuthFraudRoute: typeof AuthFraudRoute
  AuthGamificationRoute: typeof AuthGamificationRoute
  AuthLmsRoute: typeof AuthLmsRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthRubricsRoute: typeof AuthRubricsRoute
  AuthSystemRoute: typeof AuthSystemRoute
  AuthAssignmentsIdRoute: typeof AuthAssignmentsIdRoute
  AuthCertificatesCertNoRoute: typeof AuthCertificatesCertNoRoute
  AuthCoursesIdRoute: typeof AuthCoursesIdRoute
  AuthQuestionsNewRoute: typeof AuthQuestionsNewRoute
  AuthQuizTemplatesIdRoute: typeof AuthQuizTemplatesIdRoute
  AuthSubmissionsIdRoute: typeof AuthSubmissionsIdRoute
  AuthAssignmentsIndexRoute: typeof AuthAssignmentsIndexRoute
  AuthCertificatesIndexRoute: typeof AuthCertificatesIndexRoute
  AuthCoursesIndexRoute: typeof AuthCoursesIndexRoute
  AuthQuestionsIndexRoute: typeof AuthQuestionsIndexRoute
  AuthQuizTemplatesIndexRoute: typeof AuthQuizTemplatesIndexRoute
  AuthSubmissionsIndexRoute: typeof AuthSubmissionsIndexRoute
  AuthAssignmentsIdTakeRoute: typeof AuthAssignmentsIdTakeRoute
  AuthCoursesIdCurriculumRoute: typeof AuthCoursesIdCurriculumRoute
  AuthCoursesIdLearnRoute: typeof AuthCoursesIdLearnRoute
  AuthQuestionsIdEditRoute: typeof AuthQuestionsIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEnterpriseRoute: AuthEnterpriseRoute,
  AuthFraudRoute: AuthFraudRoute,
  AuthGamificationRoute: AuthGamificationRoute,
  AuthLmsRoute: AuthLmsRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthRubricsRoute: AuthRubricsRoute,
  AuthSystemRoute: AuthSystemRoute,
  AuthAssignmentsIdRoute: AuthAssignmentsIdRoute,
  AuthCertificatesCertNoRoute: AuthCertificatesCertNoRoute,
  AuthCoursesIdRoute: AuthCoursesIdRoute,
  AuthQuestionsNewRoute: AuthQuestionsNewRoute,
  AuthQuizTemplatesIdRoute: AuthQuizTemplatesIdRoute,
  AuthSubmissionsIdRoute: AuthSubmissionsIdRoute,
  AuthAssignmentsIndexRoute: AuthAssignmentsIndexRoute,
  AuthCertificatesIndexRoute: AuthCertificatesIndexRoute,
  AuthCoursesIndexRoute: AuthCoursesIndexRoute,
  AuthQuestionsIndexRoute: AuthQuestionsIndexRoute,
  AuthQuizTemplatesIndexRoute: AuthQuizTemplatesIndexRoute,
  AuthSubmissionsIndexRoute: AuthSubmissionsIndexRoute,
  AuthAssignmentsIdTakeRoute: AuthAssignmentsIdTakeRoute,
  AuthCoursesIdCurriculumRoute: AuthCoursesIdCurriculumRoute,
  AuthCoursesIdLearnRoute: AuthCoursesIdLearnRoute,
  AuthQuestionsIdEditRoute: AuthQuestionsIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
