/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSystemRouteImport } from './routes/_auth.system'
import { Route as AuthSubmissionsRouteImport } from './routes/_auth.submissions'
import { Route as AuthRubricsRouteImport } from './routes/_auth.rubrics'
import { Route as AuthReportsRouteImport } from './routes/_auth.reports'
import { Route as AuthQuizTemplatesRouteImport } from './routes/_auth.quiz-templates'
import { Route as AuthQuestionsRouteImport } from './routes/_auth.questions'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthLmsRouteImport } from './routes/_auth.lms'
import { Route as AuthGamificationRouteImport } from './routes/_auth.gamification'
import { Route as AuthFraudRouteImport } from './routes/_auth.fraud'
import { Route as AuthEnterpriseRouteImport } from './routes/_auth.enterprise'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCoursesRouteImport } from './routes/_auth.courses'
import { Route as AuthAssignmentsRouteImport } from './routes/_auth.assignments'
import { Route as AssignmentsIdTakeRouteImport } from './routes/assignments.$id.take'
import { Route as AuthSubmissionsIdRouteImport } from './routes/_auth.submissions.$id'
import { Route as AuthQuizTemplatesIdRouteImport } from './routes/_auth.quiz-templates.$id'
import { Route as AuthQuestionsNewRouteImport } from './routes/_auth.questions.new'
import { Route as AuthCoursesIdRouteImport } from './routes/_auth.courses.$id'
import { Route as AuthAssignmentsIdRouteImport } from './routes/_auth.assignments.$id'
import { Route as AuthQuestionsIdEditRouteImport } from './routes/_auth.questions.$id.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSystemRoute = AuthSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubmissionsRoute = AuthSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRubricsRoute = AuthRubricsRouteImport.update({
  id: '/rubrics',
  path: '/rubrics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuizTemplatesRoute = AuthQuizTemplatesRouteImport.update({
  id: '/quiz-templates',
  path: '/quiz-templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestionsRoute = AuthQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLmsRoute = AuthLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGamificationRoute = AuthGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFraudRoute = AuthFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEnterpriseRoute = AuthEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesRoute = AuthCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssignmentsRoute = AuthAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AuthRoute,
} as any)
const AssignmentsIdTakeRoute = AssignmentsIdTakeRouteImport.update({
  id: '/assignments/$id/take',
  path: '/assignments/$id/take',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSubmissionsIdRoute = AuthSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthSubmissionsRoute,
} as any)
const AuthQuizTemplatesIdRoute = AuthQuizTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthQuizTemplatesRoute,
} as any)
const AuthQuestionsNewRoute = AuthQuestionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthQuestionsRoute,
} as any)
const AuthCoursesIdRoute = AuthCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthCoursesRoute,
} as any)
const AuthAssignmentsIdRoute = AuthAssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthAssignmentsRoute,
} as any)
const AuthQuestionsIdEditRoute = AuthQuestionsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthQuestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/assignments': typeof AuthAssignmentsRouteWithChildren
  '/courses': typeof AuthCoursesRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/enterprise': typeof AuthEnterpriseRoute
  '/fraud': typeof AuthFraudRoute
  '/gamification': typeof AuthGamificationRoute
  '/lms': typeof AuthLmsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/questions': typeof AuthQuestionsRouteWithChildren
  '/quiz-templates': typeof AuthQuizTemplatesRouteWithChildren
  '/reports': typeof AuthReportsRoute
  '/rubrics': typeof AuthRubricsRoute
  '/submissions': typeof AuthSubmissionsRouteWithChildren
  '/system': typeof AuthSystemRoute
  '/assignments/$id': typeof AuthAssignmentsIdRoute
  '/courses/$id': typeof AuthCoursesIdRoute
  '/questions/new': typeof AuthQuestionsNewRoute
  '/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/submissions/$id': typeof AuthSubmissionsIdRoute
  '/assignments/$id/take': typeof AssignmentsIdTakeRoute
  '/questions/$id/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/assignments': typeof AuthAssignmentsRouteWithChildren
  '/courses': typeof AuthCoursesRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/enterprise': typeof AuthEnterpriseRoute
  '/fraud': typeof AuthFraudRoute
  '/gamification': typeof AuthGamificationRoute
  '/lms': typeof AuthLmsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/profile': typeof AuthProfileRoute
  '/questions': typeof AuthQuestionsRouteWithChildren
  '/quiz-templates': typeof AuthQuizTemplatesRouteWithChildren
  '/reports': typeof AuthReportsRoute
  '/rubrics': typeof AuthRubricsRoute
  '/submissions': typeof AuthSubmissionsRouteWithChildren
  '/system': typeof AuthSystemRoute
  '/assignments/$id': typeof AuthAssignmentsIdRoute
  '/courses/$id': typeof AuthCoursesIdRoute
  '/questions/new': typeof AuthQuestionsNewRoute
  '/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/submissions/$id': typeof AuthSubmissionsIdRoute
  '/assignments/$id/take': typeof AssignmentsIdTakeRoute
  '/questions/$id/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_auth/assignments': typeof AuthAssignmentsRouteWithChildren
  '/_auth/courses': typeof AuthCoursesRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/enterprise': typeof AuthEnterpriseRoute
  '/_auth/fraud': typeof AuthFraudRoute
  '/_auth/gamification': typeof AuthGamificationRoute
  '/_auth/lms': typeof AuthLmsRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/questions': typeof AuthQuestionsRouteWithChildren
  '/_auth/quiz-templates': typeof AuthQuizTemplatesRouteWithChildren
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/rubrics': typeof AuthRubricsRoute
  '/_auth/submissions': typeof AuthSubmissionsRouteWithChildren
  '/_auth/system': typeof AuthSystemRoute
  '/_auth/assignments/$id': typeof AuthAssignmentsIdRoute
  '/_auth/courses/$id': typeof AuthCoursesIdRoute
  '/_auth/questions/new': typeof AuthQuestionsNewRoute
  '/_auth/quiz-templates/$id': typeof AuthQuizTemplatesIdRoute
  '/_auth/submissions/$id': typeof AuthSubmissionsIdRoute
  '/assignments/$id/take': typeof AssignmentsIdTakeRoute
  '/_auth/questions/$id/edit': typeof AuthQuestionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/assignments'
    | '/courses'
    | '/dashboard'
    | '/enterprise'
    | '/fraud'
    | '/gamification'
    | '/lms'
    | '/onboarding'
    | '/profile'
    | '/questions'
    | '/quiz-templates'
    | '/reports'
    | '/rubrics'
    | '/submissions'
    | '/system'
    | '/assignments/$id'
    | '/courses/$id'
    | '/questions/new'
    | '/quiz-templates/$id'
    | '/submissions/$id'
    | '/assignments/$id/take'
    | '/questions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/assignments'
    | '/courses'
    | '/dashboard'
    | '/enterprise'
    | '/fraud'
    | '/gamification'
    | '/lms'
    | '/onboarding'
    | '/profile'
    | '/questions'
    | '/quiz-templates'
    | '/reports'
    | '/rubrics'
    | '/submissions'
    | '/system'
    | '/assignments/$id'
    | '/courses/$id'
    | '/questions/new'
    | '/quiz-templates/$id'
    | '/submissions/$id'
    | '/assignments/$id/take'
    | '/questions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_auth/assignments'
    | '/_auth/courses'
    | '/_auth/dashboard'
    | '/_auth/enterprise'
    | '/_auth/fraud'
    | '/_auth/gamification'
    | '/_auth/lms'
    | '/_auth/onboarding'
    | '/_auth/profile'
    | '/_auth/questions'
    | '/_auth/quiz-templates'
    | '/_auth/reports'
    | '/_auth/rubrics'
    | '/_auth/submissions'
    | '/_auth/system'
    | '/_auth/assignments/$id'
    | '/_auth/courses/$id'
    | '/_auth/questions/new'
    | '/_auth/quiz-templates/$id'
    | '/_auth/submissions/$id'
    | '/assignments/$id/take'
    | '/_auth/questions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AssignmentsIdTakeRoute: typeof AssignmentsIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/system': {
      id: '/_auth/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthSystemRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/submissions': {
      id: '/_auth/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthSubmissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rubrics': {
      id: '/_auth/rubrics'
      path: '/rubrics'
      fullPath: '/rubrics'
      preLoaderRoute: typeof AuthRubricsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quiz-templates': {
      id: '/_auth/quiz-templates'
      path: '/quiz-templates'
      fullPath: '/quiz-templates'
      preLoaderRoute: typeof AuthQuizTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/questions': {
      id: '/_auth/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthQuestionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lms': {
      id: '/_auth/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof AuthLmsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gamification': {
      id: '/_auth/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AuthGamificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fraud': {
      id: '/_auth/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof AuthFraudRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/enterprise': {
      id: '/_auth/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof AuthEnterpriseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses': {
      id: '/_auth/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthCoursesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assignments': {
      id: '/_auth/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthAssignmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/assignments/$id/take': {
      id: '/assignments/$id/take'
      path: '/assignments/$id/take'
      fullPath: '/assignments/$id/take'
      preLoaderRoute: typeof AssignmentsIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/submissions/$id': {
      id: '/_auth/submissions/$id'
      path: '/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthSubmissionsIdRouteImport
      parentRoute: typeof AuthSubmissionsRoute
    }
    '/_auth/quiz-templates/$id': {
      id: '/_auth/quiz-templates/$id'
      path: '/$id'
      fullPath: '/quiz-templates/$id'
      preLoaderRoute: typeof AuthQuizTemplatesIdRouteImport
      parentRoute: typeof AuthQuizTemplatesRoute
    }
    '/_auth/questions/new': {
      id: '/_auth/questions/new'
      path: '/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof AuthQuestionsNewRouteImport
      parentRoute: typeof AuthQuestionsRoute
    }
    '/_auth/courses/$id': {
      id: '/_auth/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthCoursesIdRouteImport
      parentRoute: typeof AuthCoursesRoute
    }
    '/_auth/assignments/$id': {
      id: '/_auth/assignments/$id'
      path: '/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AuthAssignmentsIdRouteImport
      parentRoute: typeof AuthAssignmentsRoute
    }
    '/_auth/questions/$id/edit': {
      id: '/_auth/questions/$id/edit'
      path: '/$id/edit'
      fullPath: '/questions/$id/edit'
      preLoaderRoute: typeof AuthQuestionsIdEditRouteImport
      parentRoute: typeof AuthQuestionsRoute
    }
  }
}

interface AuthAssignmentsRouteChildren {
  AuthAssignmentsIdRoute: typeof AuthAssignmentsIdRoute
}

const AuthAssignmentsRouteChildren: AuthAssignmentsRouteChildren = {
  AuthAssignmentsIdRoute: AuthAssignmentsIdRoute,
}

const AuthAssignmentsRouteWithChildren = AuthAssignmentsRoute._addFileChildren(
  AuthAssignmentsRouteChildren,
)

interface AuthCoursesRouteChildren {
  AuthCoursesIdRoute: typeof AuthCoursesIdRoute
}

const AuthCoursesRouteChildren: AuthCoursesRouteChildren = {
  AuthCoursesIdRoute: AuthCoursesIdRoute,
}

const AuthCoursesRouteWithChildren = AuthCoursesRoute._addFileChildren(
  AuthCoursesRouteChildren,
)

interface AuthQuestionsRouteChildren {
  AuthQuestionsNewRoute: typeof AuthQuestionsNewRoute
  AuthQuestionsIdEditRoute: typeof AuthQuestionsIdEditRoute
}

const AuthQuestionsRouteChildren: AuthQuestionsRouteChildren = {
  AuthQuestionsNewRoute: AuthQuestionsNewRoute,
  AuthQuestionsIdEditRoute: AuthQuestionsIdEditRoute,
}

const AuthQuestionsRouteWithChildren = AuthQuestionsRoute._addFileChildren(
  AuthQuestionsRouteChildren,
)

interface AuthQuizTemplatesRouteChildren {
  AuthQuizTemplatesIdRoute: typeof AuthQuizTemplatesIdRoute
}

const AuthQuizTemplatesRouteChildren: AuthQuizTemplatesRouteChildren = {
  AuthQuizTemplatesIdRoute: AuthQuizTemplatesIdRoute,
}

const AuthQuizTemplatesRouteWithChildren =
  AuthQuizTemplatesRoute._addFileChildren(AuthQuizTemplatesRouteChildren)

interface AuthSubmissionsRouteChildren {
  AuthSubmissionsIdRoute: typeof AuthSubmissionsIdRoute
}

const AuthSubmissionsRouteChildren: AuthSubmissionsRouteChildren = {
  AuthSubmissionsIdRoute: AuthSubmissionsIdRoute,
}

const AuthSubmissionsRouteWithChildren = AuthSubmissionsRoute._addFileChildren(
  AuthSubmissionsRouteChildren,
)

interface AuthRouteChildren {
  AuthAssignmentsRoute: typeof AuthAssignmentsRouteWithChildren
  AuthCoursesRoute: typeof AuthCoursesRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEnterpriseRoute: typeof AuthEnterpriseRoute
  AuthFraudRoute: typeof AuthFraudRoute
  AuthGamificationRoute: typeof AuthGamificationRoute
  AuthLmsRoute: typeof AuthLmsRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthQuestionsRoute: typeof AuthQuestionsRouteWithChildren
  AuthQuizTemplatesRoute: typeof AuthQuizTemplatesRouteWithChildren
  AuthReportsRoute: typeof AuthReportsRoute
  AuthRubricsRoute: typeof AuthRubricsRoute
  AuthSubmissionsRoute: typeof AuthSubmissionsRouteWithChildren
  AuthSystemRoute: typeof AuthSystemRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAssignmentsRoute: AuthAssignmentsRouteWithChildren,
  AuthCoursesRoute: AuthCoursesRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEnterpriseRoute: AuthEnterpriseRoute,
  AuthFraudRoute: AuthFraudRoute,
  AuthGamificationRoute: AuthGamificationRoute,
  AuthLmsRoute: AuthLmsRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthQuestionsRoute: AuthQuestionsRouteWithChildren,
  AuthQuizTemplatesRoute: AuthQuizTemplatesRouteWithChildren,
  AuthReportsRoute: AuthReportsRoute,
  AuthRubricsRoute: AuthRubricsRoute,
  AuthSubmissionsRoute: AuthSubmissionsRouteWithChildren,
  AuthSystemRoute: AuthSystemRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AssignmentsIdTakeRoute: AssignmentsIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
